### ISSUE TITLE
Related to issue #1: The SDK does not seem to build out of the box

### ISSUE THREAD

**Issue by jensemil** [microsoft/Cognitive-CustomVision-Windows#2]
Related to issue #1 - I wanted to include a local build of the SDK with the sample, however, it does not build.

I tried to build the SDK from two different machines - a Windows PC and a Windows Server, both with the newest Visual Studio 2017 installed. They both returned the following errors:
![sdk-error-windows-server](https://cloud.githubusercontent.com/assets/6105088/26152832/a38131d0-3b00-11e7-96ba-6d6a72dc7e37.PNG)

It looks like it is trying to use some modules within the SDK that is neither self-contained nor referenced in the list of references.

**Comment by chsienki** [comment]
The SDK is autogenerated using https://github.com/Azure/AutoRest 

We're only shipping the non-generated components here; you need to generate before the sln will build. I'll add a readme with instructions for building

**Comment by rrvenki** [comment]
Same here - Client library does not build out of box.
If I use the client libraries from nuget, in below 2 lines of my code for prediction, the second line throws error.

`Dim iOnImage As New MemoryStream(File.ReadAllBytes(iCurImg.ImgFile))

Dim PredRes = PrdEndPoint.PredictImage(TrgProject.id, iOnImage)`

The error returned is
Message: Operation returned an invalid status code 'NotFound'

Stack trace:    at Microsoft.Cognitive.CustomVision.PredictionEndpoint.<PredictImageWithHttpMessagesAsync>d__28.MoveNext() in C:\projects\IRIS\Iris.SDK\CustomVisionSDK\Cognitive-CustomVision-Windows\ClientLibrary\Microsoft.Cognitive.CustomVision.Prediction\Generated\PredictionEndpoint.cs:line 597
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Cognitive.CustomVision.PredictionEndpointExtensions.<PredictImageAsync>d__4.MoveNext() in C:\projects\IRIS\Iris.SDK\CustomVisionSDK\Cognitive-CustomVision-Windows\ClientLibrary\Microsoft.Cognitive.CustomVision.Prediction\Generated\PredictionEndpointExtensions.cs:line 151
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Cognitive.CustomVision.PredictionEndpointExtensions.PredictImage(IPredictionEndpoint operations, Guid projectId, Stream imageData, Nullable`1 iterationId, String application) in C:\projects\IRIS\Iris.SDK\CustomVisionSDK\Cognitive-CustomVision-Windows\ClientLibrary\Microsoft.Cognitive.CustomVision.Prediction\Generated\PredictionEndpointExtensions.cs:line 125
   at SBToiletFinder.MainWindow.VB$StateMachine_17_ProcessToiletConfidence.MoveNext() in F:\Projects\MyProject\MyProject\MainWindow.xaml.vb:line 317

Awaiting next build at the earliest.

**Comment by chsienki** [comment]
That looks like you don't have a default iteration set on your project. Either select an iteration to be the default, or pass in an explicit iteration id to your PredictImage call.

**Comment by rrvenki** [comment]
Hi, Thanks for that quick response.  Now I changed the code
Dim PredRes = PrdEndPoint.PredictImage(TrgProject.id, iOnImage)
to
Dim PredRes = PrdEndPoint.PredictImage(TrgProject.Id, iOnImage, TrgProject.CurrentIterationId, TrgProject.Name)
Checked all parameters in debug and found correct values are passed.  However still it gives the same error.  In the site the iteration count is 6 and it is the default.
Any help would be appreciated.

**Comment by chsienki** [comment]
CurrentIterationId is misleading; it's not the last trained iteration, but the iteration that is about to be trained. Asking for a prediction from it will fail by its very nature, as it's not been trained yet.

You can get the iteration id of a given iteration by selecting it in the UI, choosing 'Prediction URL' and copying the last part of the url that says 'iterationId='  

Alternatively you can use the API to call GetIterations(), and get the ID from one of the objects in the list returned.
